package org.openrewrite.config

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory
import com.fasterxml.jackson.module.kotlin.readValue
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import java.io.File

/**
 * Configuration for whitelabeling the documentation site.
 * All brand-specific text and URLs are configurable.
 */
data class BrandingConfig(
    /** Organization name displayed in documentation */
    val organizationName: String = "OpenRewrite",
    /** Base URL for the documentation site */
    val docsBaseUrl: String = "https://docs.openrewrite.org",
    /** Base URL for the application platform */
    val appBaseUrl: String = "https://app.moderne.io",
    /** Name of the CLI tool */
    val cliName: String = "Moderne CLI",
    /** URL for CLI documentation */
    val cliDocsUrl: String = "https://docs.moderne.io/user-documentation/moderne-cli/getting-started/cli-intro",
    /** Platform name (e.g., "Moderne") */
    val platformName: String = "Moderne",
    /** Contact URL for the platform */
    val contactUrl: String = "https://moderne.io/product",
    /** Whether to show platform-specific sections (e.g., Moderne link) */
    val showPlatformSections: Boolean = true,
    /** Custom component import for recipe callout (empty to disable) */
    val recipeCalloutImport: String = "import RecipeCallout from '@site/src/components/ModerneLink';",
    /** Template for recipe callout component (use {recipeName} placeholder) */
    val recipeCalloutTemplate: String = "<RecipeCallout link=\"{appBaseUrl}/recipes/{recipeName}\" />",
    /** Tab import statement for the documentation framework */
    val tabsImport: String = "import Tabs from '@theme/Tabs';\nimport TabItem from '@theme/TabItem';",
    /** Description prefix for the versions page */
    val versionsPageDescription: String = "An autogenerated table with the latest version of each OpenRewrite module.",
    /** The Maven Central search URL */
    val mavenCentralUrl: String = "https://search.maven.org/search?q=org.openrewrite",
    /** GitHub organization URL for repositories */
    val githubOrgUrl: String = "https://github.com/openrewrite",
    /** CLI releases API URL */
    val cliReleasesApiUrl: String = "https://api.github.com/repos/moderneinc/moderne-cli-releases/releases"
) {
    companion object {
        fun load(configFile: File?): BrandingConfig {
            if (configFile == null || !configFile.exists()) {
                return BrandingConfig()
            }
            val mapper = ObjectMapper(YAMLFactory()).registerKotlinModule()
            return mapper.readValue(configFile)
        }
    }
}
